# Teleop configuration for xbox one controller
teleop_twist_joy:
  axis_linear: 5
  scale_linear: 1.0
  scale_linear_turbo: 2.0
  axis_angular: 0
  scale_angular: 1.4
  enable_button: 1
  enable_turbo_button: 2