# Overall filter
odom_frame_id: "odom"
odom_model_type: "diff-corrected"
base_frame_id: "robot_footprint"
global_frame_id: "map"

min_particles: 100  # Default: 100 particles
max_particles: 5000  # Default: 5000 particles    (Dropping number shows noticable loss in AMCL performance)
initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: 0.0
update_min_d: 0.05  # Default: 0.2 m    (Large effect on AMCL)
update_min_a: 0.1  # Default: 0.52 radians    (Large effect on AMCL)
recovery_alpha_slow: 0  # Default: 0
recovery_alpha_fast: 0  # Default: 0
transform_tolerance: 1  # Default: 0.1 s
kld_err: 0.05  # Default: 0.01 | Maximum error between the true distribution and the estimated distribution.    (Large effect on AMCL)
resample_interval: 2  # Default: 2    (Higher or lower makes AMCL worse)

odom_alpha1: 0.3  # Default: 0.2 | expected noise in odometry's rotation estimate from the rotation
odom_alpha2: 0.2  # Default: 0.2 | expected noise in odometry's rotation estimate from translation
odom_alpha3: 0.2  # Default: 0.2 | expected noise in odometry's translation estimate from the translation
odom_alpha4: 0.25  # Default: 0.2 | expected noise in odometry's translation estimate from the rotation

# Laser
laser_min_range: -1  # Default: -1 (use sensor info)
laser_max_range: -1  # Default: -1 (use sensor info)
laser_max_beams: 50  # Default: 30 beams
laser_z_hit: 0.95 # Default: 0.95 | Laser beams hits obstacle (good for un-dynamic environments)
laser_z_rand: 0.01 # Default: 0.05 | Uniform distribution for unmodelled detections
laser_likelihood_max_dist: 2.0  # Default: 2.0 m | Maximum distance to do obstacle inflation on map

# use_map_topic: true
tf_broadcast: true