map_type: costmap

obstacle_range: 2.5 # Default: 2.5 m
raytrace_range: 3.0 # Default: 3.0 m

transform_tolerance: 1.0  # Default: 0.2 s

footprint: [[0.25, 0.20], [0.25, -0.20], [-0.25, -0.20], [-0.25, 0.20]]
# robot_radius: 0.3

# inflation_radius: 0.4  # Default: 0.55 m
# cost_scaling_factor: 8.0  # Default: 10.0 (5 used)

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: scan, marking: true, clearing: true}
