global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 2.0  # Default: 5.0 Hz
   publish_frequency: 2.0  # Default: 0 Hz
   width: 20.0
   height: 20.0
   resolution: 0.05
   static_map: true
   rolling_window: false

   inflation_radius: 0.5  # Default: 0.55 m
   cost_scaling_factor: 8.0  # Default: 10.0 (5 used)
