      odom_frame: odom
      base_frame: robot_footprint
      map_frame: map

      map_update_interval: 2.0 # Default: 5.0s | Time between map updates | Publish new map

      maxUrange: 5.0 # Default: 80.0 | Max usable laser range | Should be just less than sensor range
      maxRange: 6.0 # Max range of sensor | Should be just greater than laser range
      particles: 100 # Default: 30 particles

      # Update frequencies
      linearUpdate: 0.5  # Default: 1.0 | Process a scan each time the robot translates this far
      angularUpdate: 0.2  # Default:0.5 | Process a scan each time the robot rotates this far
      temporalUpdate: 1.0  #  Default: -1 s | Process a scan if the last scan processed is older than the update time. <0 turns this off.
      resampleThreshold: 0.5  # Default: 0.5 | The Neff based resampling threshold

      # Initial Map Size
      xmin: -100.0
      ymin: -100.0
      xmax: 100.0
      ymax: 100.0
      delta: 0.05  # Default: 0.05 m/grid | Resolution of the map

      # All default
      sigma: 0.05
      kernelSize: 1
      lstep: 0.05
      astep: 0.05
      iterations: 5
      lsigma: 0.075
      ogain: 3.0
      lskip: 0
      llsamplerange: 0.01
      llsamplestep: 0.01
      lasamplerange: 0.005
      lasamplestep: 0.005